version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: veovis/clamav
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build Docker image
          command: docker build --pull -t $IMAGE_NAME:${CIRCLE_TAG:-latest} .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME:${CIRCLE_TAG:-latest}
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:${CIRCLE_TAG:-latest}
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-latest:
          context:
            - kveer-dockerhub
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/

